name: menu_arxan_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_slidable: ^2.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  http_parser: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo-arxan.png
